Repository In-N-Out-Dev/PortfolioHub, pull requests merged in 2023-04, with the labels that each got.

#5 Layout/side bar and content
  src/App.tsx
  src/components/Container.tsx
  src/components/Home.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SideNav.tsx
  src/styles/theme.tsx
Labels: 리뷰 요청

#11 Initial settings/update css unit
  src/components/common/Divider.tsx
  src/components/common/Header.tsx
  src/components/common/InfoCard.tsx
  src/components/common/Layout.tsx
  src/components/common/StackButton.tsx
  src/components/introduce/IntroContents.tsx
  src/components/skills/Skills.tsx
  src/components/skills/SkillsCategory.tsx
  src/components/skills/SkillsCategoryItem.tsx
  src/components/skills/SkillsCategoryItemList.tsx
  src/components/skills/SkillsCategoryList.tsx
  src/styles/global.tsx
  src/styles/theme.tsx
Labels: 머지 요청

#12 Blog/ add UI
  src/components/Home.tsx
  src/components/blog/Blog.tsx
  src/components/blog/BlogContents.tsx
  src/components/blog/BlogItem.tsx
  src/components/blog/blogMockData.ts
  src/components/common/ListCard.tsx
  src/components/common/SectionTitle.tsx
  src/styles/theme.tsx
Labels: 리뷰 요청

#15 feat: add portfolio section w/ mock data
  src/assets/ForwardIcon.tsx
  src/assets/GalleryIcon.tsx
  src/assets/ListIcon.tsx
  src/assets/MailIcon.tsx
  src/components/introduce/IntroContents.tsx
  src/components/portfolio/PortfoiloData.ts
  src/components/portfolio/Portfolio.tsx
  src/components/portfolio/PortfolioContents.tsx
  src/components/portfolio/PortfolioHeader.tsx
  src/components/portfolio/gallery/PortfolioGallery.tsx
  src/components/portfolio/gallery/card/PortfolioCardFolded.tsx
  src/components/portfolio/gallery/card/PortfolioCardList.tsx
  src/components/portfolio/gallery/card/PortfolioCardOpened.tsx
  src/components/portfolio/gallery/card/PortfolioCardSkills.tsx
  src/hooks/.gitkeep
  src/hooks/index.ts
  src/hooks/usePortfolioGallery.ts
  src/styles/theme.tsx
  src/types/.gitkeep
  src/types/portfolio.ts
  src/types/props.ts
Labels: 머지 요청

#13 add introduce section2 layouts
  src/assets/LinkIcon.tsx
  src/components/Home.tsx
  src/components/career/Career.tsx
  src/components/career/CareerContents.tsx
  src/components/career/careerData.ts
  src/components/common/Divider.tsx
  src/components/common/InfoCard.tsx
  src/components/introduce/IntroContents.tsx
  src/components/introduce/Introduce.tsx
  src/components/introduce/introduceData.ts
  src/components/project/Project.tsx
  src/components/project/ProjectContents.tsx
  src/components/project/projectData.ts
Labels: 수정 요청

#17 Feat: add dark mode toggler
  package.json
  src/App.tsx
  src/components/common/Layout.tsx
  src/components/header/Header.tsx
  src/components/header/ThemeToggleButton.tsx
  src/main.tsx
  src/stores/idex.ts
  src/stores/useThemeStore.ts
  src/styles/theme.tsx
  yarn.lock
Labels: 머지 요청

#18 Header/detailed interaction
  src/assets/GalleryIcon.tsx
  src/assets/LinkIcon.tsx
  src/assets/ListIcon.tsx
  src/assets/MailIcon.tsx
  src/components/blog/BlogContents.tsx
  src/components/blog/BlogItem.tsx
  src/components/blog/blogMockData.ts
  src/components/header/ContactButton.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderData.ts
Labels: 수정 요청
